[phases.setup]
nixPkgs = [
  "chromium",
  "chromedriver",
  "python311",
  "python311Packages.pip"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python login_bot.py"
